### ISSUE TITLE
Rearrange the exception catching to go from specific to generic faults

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/wisdom-cli#20]
An inverted funnel approach would help the users to know what exactly has gone wrong when it does.

**Comment by niyonx** [comment]
Hi @t0xic0der , isn't it already this way? HTTPTimeoutError > RedirectError > PageError > DisambiguationError > Exception

**Comment by gridhead** [comment]
I'm not sure if that is the right sequence. We could close this issue if it is a correct sequence, or let folks rearrange if it is not. What do you think? :sweat_smile:

**Comment by niyonx** [comment]
I might be wrong but it seems as long as Exception is last, the rest is good since they are not a subset of one another. They will be entered if they simply match the exception. 

However, I think it would make sense to have PageError > DisambiguationError > RedirectError > HTTPTiemoutError > Exception I think. Let me know if you want me to work on it. :smile:

**Comment by gridhead** [comment]
> I might be wrong but it seems as long as Exception is last, the rest is good since they are not a subset of one another. They will be entered if they simply match the exception.

Exactly. `Exception` is the most generic of them all, so having it in the end is mandatory. The remaining exceptions are most likely not subset of each other and the documentation does not really tell much about it too. :cry: 

> However, I think it would make sense to have PageError > DisambiguationError > RedirectError > HTTPTiemoutError > Exception I think. Let me know if you want me to work on it. smile

Sure. If you think that is the right order, I am assigning you this issue. Feel free to give :star:  to this repo.

**Comment by gridhead** [comment]
Any updates, @niyonx?
